### ISSUE TITLE
Middle-ground between GraphQLInt and BigInt?

### ISSUE THREAD

**Issue by ldiqual** [Urigo/graphql-scalars#425]
I would like to use integers that are more than 32-bit, but without having to process BigInts at all. I would like a JSON number to be sent over the wire (instead of strings), and a JS Number to be processed at the resolver level (instead of BigInt *or* Number depending on platform support). This would mean 53-bit Number everywhere.

Would you consider allowing an option to the `BigInt` scalar that would serialize to Number and parse to Number? Or maybe another scalar like `Int53`? Thank you

**Comment by danielrearden** [comment]
@ldiqual Thanks for opening an issue.

The reason `BigInt` exists in JavaScript is because any Number larger than `Number.MIN_SAFE_INTEGER` (9,007,199,254,740,991) or smaller than `Number.MIN_SAFE_INTEGER` (-9,007,199,254,740,991) is considered *unsafe*. From [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER):

> Safe in this context refers to the ability to represent integers exactly and to correctly compare them. For example, `Number.MAX_SAFE_INTEGER + 1 === Number.MAX_SAFE_INTEGER + 2` will evaluate to `true`, which is mathematically incorrect.

This applies to both client-side and server-side JavaScript. Because handling "unsafe" Numbers like this can result in runtime errors, it's generally a bad idea. We could potentially add an "UnsafeInt" scalar, but I don't think it's a good idea because it doesn't reflect best practices.

**Comment by ldiqual** [comment]
@danielrearden Thanks a lot for following up on this! Agreed with what you said here, I don't think we should be using Number for values over 2^53-1, but at the moment there's no alternative for numbers between 2^32 (max for GraphQLInt) and 2^53 (max safe integer for JS Number), which is quite a big range. So I guess what I'm asking is whether we could have a safe integer scalar for values between -2^53 and 2^53?

**Comment by danielrearden** [comment]
@ldiqual Sorry, I misunderstood you. Thanks for clarifying. I think it would make sense to add a `SafeInteger` scalar that was `specifiedBy` the [ECMAScript spec](https://www.ecma-international.org/ecma-262/#sec-number.issafeinteger).

**Comment by ldiqual** [comment]
@danielrearden amazing stuff! Thank you so much for adding this, it'll be super helpful.
@ardatan when is the next release planned? Just wondering if we should use master in the meantime or just wait a bit

**Comment by ardatan** [comment]
Available in v1.2.4!
