### ISSUE TITLE
Generate mocks

### ISSUE THREAD

**Issue by lookfirst** [Urigo/graphql-scalars#57]
I'm not sure how to do this, but it would be cool if this project had a way to automatically define mocks as well.

https://www.apollographql.com/docs/apollo-server/features/mocking/

**Comment by ardatan** [comment]
It is not possible to make those scalars automatically mocked because default ones are defined hardcoded in that line 
https://github.com/apollographql/graphql-tools/blob/b8307876e6b5410ce6b1f924d656f2b6624791f7/src/mock.ts#L52
But it is possible to export something like `mocks` to pass to ApolloServer or any other implementation that does mocking.

**Comment by lookfirst** [comment]
Exporting something is fine.

**Comment by lookfirst** [comment]
This might also be something you pass up to the Apollo people as a feature request. People should be able to build scalars that include their own mocks.

**Comment by ardatan** [comment]
Until it gets released, you can use the following versions for mocking functions;
`0.4.8-f38f1db.0`
They're exported under the name `mocks`

**Comment by ardatan** [comment]
Available in 1.0.0!

**Comment by lookfirst** [comment]
Beautiful
