### ISSUE TITLE
Convert Emails to lowercase in the EmailAddress custom type

### ISSUE THREAD

**Issue by williamkwao** [Urigo/graphql-scalars#64]
Since emails are not case sensitive, I was wondering if it will be good to convert emails to lowercase in the EmailAddress  parseValue and parseLiteral functions. This will be handy for saving the email addresses in databases without having to do any extra parsing. I can make a PR for this if you think this is a useful feature to add

**Comment by ardatan** [comment]
@williamkwao I think the input should already be lowercased before sending to the server so that the database will keep those in valid format which will be sent by the server without any problems as well. So wouldn't it be better to keep this kind of validations on the client side?

**Comment by williamkwao** [comment]
@ardatan I agree that this should be handled by the client but its good practice to handle it on both sides and not fully trust the client. I had to do this working on a recent project and thought it'll be nice if it was handled by the custom scalar.

**Comment by Urigo** [comment]
@williamkwao everything you say is correct, but I believe `graphql-scalars` is about validating and not conversion...
And actually I'm not sure validating on the API level is the right place because I can think of some use cases where apps would want to send it not as lower case.

So my current thought is that you are right but this library is not the right place to take care of that.

But please try to convince me otherwise, I'm keeping it open for now

**Comment by Urigo** [comment]
I thought about it more and I'm starting to doubt myself...
I hope to get more feedback

**Comment by lookfirst** [comment]
Don't mutate my data unless I ask for it please. Principle of least surprises.

**Comment by Urigo** [comment]
very true @lookfirst !

**Comment by mmahalwy** [comment]
maybe there could be an option to mutate? :)
