### ISSUE TITLE
DateTime cannot represent an invalid date-time-string

### ISSUE THREAD

**Issue by JinW-Airwallex** [Urigo/graphql-scalars#929]
**Describe the bug**
Based on https://github.com/Urigo/graphql-scalars/issues/395, DateTimeResolver should be able to accept 2021-06-23T05:50:47.918+0000. But it appears the latest version will complain that the string is invalid.

**To Reproduce**

require('graphql')
const { DateTimeResolver } = require('graphql-scalars')
DateTimeResolver.parseValue('2021-06-23T05:50:47.918+0000')

**Expected behavior**
No errors

**Environment:**

- OS: 
- GraphQL Scalars Version: 1.10.1
- NodeJS: 12.22.0

**Comment by justdvl** [comment]
Until this is fixed, a workaround solution that works for me is sending just YYYY-MM-DD ("2021-09-01") from FE to Server.

**Comment by shaunpersad** [comment]
Any update on this issue? The `+0000` suffix is fairly common in the wild, and it makes the `DateTime` scalar a liability to use. We had to define our own scalar instead.

**Comment by ardatan** [comment]
@shaunpersad Is it valid for the spec we follow?

**Comment by shaunpersad** [comment]
It should be, as the `Z` suffix is equivalent to a `0` offset, which could be represented as `+0000`, `+00:00`, etc. according to the ISO-8601 spec. Unfortunately I cannot view the full spec without purchasing it, but the wikipedia on it does say:
```
An offset of zero, in addition to having the special representation "Z", can also be stated numerically as "+00:00", "+0000", or "+00". However, it is not permitted to state it numerically with a negative sign, as "−00:00", "−0000", or "−00".
```

**Comment by shaunpersad** [comment]
Is there any more information I can provide to help?

**Comment by tvvignesh** [comment]
@ardatan Hi. You can assign this to me, I will have a look.

**Comment by tvvignesh** [comment]
I had a look at this issue. Currently `graphql-scalars` adopts `RFC 3339` spec of DateTime as mentioned here: https://github.com/Urigo/graphql-scalars/blob/master/website/docs/scalars/date-time.md

As per the spec, this should be the format:
![image](https://user-images.githubusercontent.com/1165845/145953413-d8bde415-fc76-414a-ab3b-61592b912ee6.png)

So, `2021-06-23T05:50:47.918+00:00` is valid since it has a colon separator in fractional seconds but `2021-06-23T05:50:47.918+0000` is not since there is no separator

![image](https://user-images.githubusercontent.com/1165845/145954261-5dec40ae-fd43-49a5-a5aa-67ae78e7d5cd.png)

When expanding the full DateTime format, this is what it expands to: `date-fullyear "-" date-month "-" date-mday T time-hour ":" time-minute ":" time-second[time-secfrac] "Z" / time-numoffset` which the current regex does support when used with colon.

**Comment by fierysolid** [comment]
If anyone finds this issue and they don't use dates with the colon, you can go add a `?` directly behind the last colon in the  `RFC_3339_REGEX` regex in `validateDateTime` and directly behind the last colon in the `TIME_REGEX` regex in `validateTime` for both **index.js** and **index.mjs**, then use [patch-package](https://github.com/ds300/patch-package) to solidify it. Doesn't seem like they're going to adjust the regex to allow both since its not RFC 3339
